[package]
name = "openvr_sys"
version = "1.0.1"
authors = [
    "Colin Sherratt",
    "Erick Tryzelaar",
    "Rene Eichhorn"
]
license = "MIT"
description = "Raw unsafe system binding for openvr"
repository = "https://github.com/rust-openvr/rust-openvr-sys"

build = "build.rs"

[lib]
name = "openvr_sys"
path = "lib.rs"
